//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Service.GSP2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSBase", Namespace="http://www.chtd.com.tw")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Service.GSP2.ConfirmResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Service.GSP2.ConfirmResponse))]
    public partial class WSBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmResult", Namespace="http://www.chtd.com.tw")]
    [System.SerializableAttribute()]
    public partial class ConfirmResult : ES.Service.GSP2.WSBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApproveNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SettleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OthersField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionKey {
            get {
                return this.SessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionKeyField, value) != true)) {
                    this.SessionKeyField = value;
                    this.RaisePropertyChanged("SessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string InfoNO {
            get {
                return this.InfoNOField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoNOField, value) != true)) {
                    this.InfoNOField = value;
                    this.RaisePropertyChanged("InfoNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TransactionResult {
            get {
                return this.TransactionResultField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionResultField, value) != true)) {
                    this.TransactionResultField = value;
                    this.RaisePropertyChanged("TransactionResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ApproveNo {
            get {
                return this.ApproveNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApproveNoField, value) != true)) {
                    this.ApproveNoField = value;
                    this.RaisePropertyChanged("ApproveNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AuthDate {
            get {
                return this.AuthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthDateField, value) != true)) {
                    this.AuthDateField = value;
                    this.RaisePropertyChanged("AuthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string SettleDate {
            get {
                return this.SettleDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SettleDateField, value) != true)) {
                    this.SettleDateField = value;
                    this.RaisePropertyChanged("SettleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string HostTime {
            get {
                return this.HostTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.HostTimeField, value) != true)) {
                    this.HostTimeField = value;
                    this.RaisePropertyChanged("HostTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Others {
            get {
                return this.OthersField;
            }
            set {
                if ((object.ReferenceEquals(this.OthersField, value) != true)) {
                    this.OthersField = value;
                    this.RaisePropertyChanged("Others");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfirmResponse", Namespace="http://www.chtd.com.tw")]
    [System.SerializableAttribute()]
    public partial class ConfirmResponse : ES.Service.GSP2.WSBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES.Service.GSP2.ConfirmResult[] ConfirmResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultInfo {
            get {
                return this.ResultInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultInfoField, value) != true)) {
                    this.ResultInfoField = value;
                    this.RaisePropertyChanged("ResultInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ES.Service.GSP2.ConfirmResult[] ConfirmResults {
            get {
                return this.ConfirmResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmResultsField, value) != true)) {
                    this.ConfirmResultsField = value;
                    this.RaisePropertyChanged("ConfirmResults");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.chtd.com.tw", ConfigurationName="Service.GSP2.AccountingServiceSoap")]
    public interface AccountingServiceSoap {
        
        // CODEGEN: 命名空間 http://www.chtd.com.tw 的元素名稱  ConnectionAccount 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://www.chtd.com.tw/ConfirmTransaction", ReplyAction="*")]
        ES.Service.GSP2.ConfirmTransactionResponse ConfirmTransaction(ES.Service.GSP2.ConfirmTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmTransaction", Namespace="http://www.chtd.com.tw", Order=0)]
        public ES.Service.GSP2.ConfirmTransactionRequestBody Body;
        
        public ConfirmTransactionRequest() {
        }
        
        public ConfirmTransactionRequest(ES.Service.GSP2.ConfirmTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.chtd.com.tw")]
    public partial class ConfirmTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConnectionAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ConnectionPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SessionTransactionKey;
        
        public ConfirmTransactionRequestBody() {
        }
        
        public ConfirmTransactionRequestBody(string ConnectionAccount, string ConnectionPwd, string SessionTransactionKey) {
            this.ConnectionAccount = ConnectionAccount;
            this.ConnectionPwd = ConnectionPwd;
            this.SessionTransactionKey = SessionTransactionKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmTransactionResponse", Namespace="http://www.chtd.com.tw", Order=0)]
        public ES.Service.GSP2.ConfirmTransactionResponseBody Body;
        
        public ConfirmTransactionResponse() {
        }
        
        public ConfirmTransactionResponse(ES.Service.GSP2.ConfirmTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.chtd.com.tw")]
    public partial class ConfirmTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ES.Service.GSP2.ConfirmResponse ConfirmTransactionResult;
        
        public ConfirmTransactionResponseBody() {
        }
        
        public ConfirmTransactionResponseBody(ES.Service.GSP2.ConfirmResponse ConfirmTransactionResult) {
            this.ConfirmTransactionResult = ConfirmTransactionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountingServiceSoapChannel : ES.Service.GSP2.AccountingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingServiceSoapClient : System.ServiceModel.ClientBase<ES.Service.GSP2.AccountingServiceSoap>, ES.Service.GSP2.AccountingServiceSoap {
        
        public AccountingServiceSoapClient() {
        }
        
        public AccountingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES.Service.GSP2.ConfirmTransactionResponse ES.Service.GSP2.AccountingServiceSoap.ConfirmTransaction(ES.Service.GSP2.ConfirmTransactionRequest request) {
            return base.Channel.ConfirmTransaction(request);
        }
        
        public ES.Service.GSP2.ConfirmResponse ConfirmTransaction(string ConnectionAccount, string ConnectionPwd, string SessionTransactionKey) {
            ES.Service.GSP2.ConfirmTransactionRequest inValue = new ES.Service.GSP2.ConfirmTransactionRequest();
            inValue.Body = new ES.Service.GSP2.ConfirmTransactionRequestBody();
            inValue.Body.ConnectionAccount = ConnectionAccount;
            inValue.Body.ConnectionPwd = ConnectionPwd;
            inValue.Body.SessionTransactionKey = SessionTransactionKey;
            ES.Service.GSP2.ConfirmTransactionResponse retVal = ((ES.Service.GSP2.AccountingServiceSoap)(this)).ConfirmTransaction(inValue);
            return retVal.Body.ConfirmTransactionResult;
        }
    }
}
