//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ES.Service.GSP1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentInfo", Namespace="http://www.chtd.com.tw")]
    [System.SerializableAttribute()]
    public partial class PaymentInfo : ES.Service.GSP1.WSBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SOIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoNOField;
        
        private int AmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIDField, value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SOID {
            get {
                return this.SOIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SOIDField, value) != true)) {
                    this.SOIDField = value;
                    this.RaisePropertyChanged("SOID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string InfoNO {
            get {
                return this.InfoNOField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoNOField, value) != true)) {
                    this.InfoNOField = value;
                    this.RaisePropertyChanged("InfoNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSBase", Namespace="http://www.chtd.com.tw")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Service.GSP1.SessionKeyResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Service.GSP1.SessionKeyResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ES.Service.GSP1.PaymentInfo))]
    public partial class WSBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionKeyResult", Namespace="http://www.chtd.com.tw")]
    [System.SerializableAttribute()]
    public partial class SessionKeyResult : ES.Service.GSP1.WSBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoNOField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionKey {
            get {
                return this.SessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionKeyField, value) != true)) {
                    this.SessionKeyField = value;
                    this.RaisePropertyChanged("SessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string InfoNO {
            get {
                return this.InfoNOField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoNOField, value) != true)) {
                    this.InfoNOField = value;
                    this.RaisePropertyChanged("InfoNO");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionKeyResponse", Namespace="http://www.chtd.com.tw")]
    [System.SerializableAttribute()]
    public partial class SessionKeyResponse : ES.Service.GSP1.WSBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTransactionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ES.Service.GSP1.SessionKeyResult[] SessionKeyResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultInfo {
            get {
                return this.ResultInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultInfoField, value) != true)) {
                    this.ResultInfoField = value;
                    this.RaisePropertyChanged("ResultInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SessionTransactionKey {
            get {
                return this.SessionTransactionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTransactionKeyField, value) != true)) {
                    this.SessionTransactionKeyField = value;
                    this.RaisePropertyChanged("SessionTransactionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ES.Service.GSP1.SessionKeyResult[] SessionKeyResults {
            get {
                return this.SessionKeyResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionKeyResultsField, value) != true)) {
                    this.SessionKeyResultsField = value;
                    this.RaisePropertyChanged("SessionKeyResults");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.chtd.com.tw", ConfigurationName="Service.GSP1.TransactionServiceSoap")]
    public interface TransactionServiceSoap {
        
        // CODEGEN: 命名空間 http://www.chtd.com.tw 的元素名稱  ConnectionAccount 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="http://www.chtd.com.tw/GetSessionTransactionKey", ReplyAction="*")]
        ES.Service.GSP1.GetSessionTransactionKeyResponse GetSessionTransactionKey(ES.Service.GSP1.GetSessionTransactionKeyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionTransactionKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSessionTransactionKey", Namespace="http://www.chtd.com.tw", Order=0)]
        public ES.Service.GSP1.GetSessionTransactionKeyRequestBody Body;
        
        public GetSessionTransactionKeyRequest() {
        }
        
        public GetSessionTransactionKeyRequest(ES.Service.GSP1.GetSessionTransactionKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.chtd.com.tw")]
    public partial class GetSessionTransactionKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConnectionAccount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ConnectionPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClientIP;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ROCID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ES.Service.GSP1.PaymentInfo[] info;
        
        public GetSessionTransactionKeyRequestBody() {
        }
        
        public GetSessionTransactionKeyRequestBody(string ConnectionAccount, string ConnectionPwd, string ClientIP, string ROCID, ES.Service.GSP1.PaymentInfo[] info) {
            this.ConnectionAccount = ConnectionAccount;
            this.ConnectionPwd = ConnectionPwd;
            this.ClientIP = ClientIP;
            this.ROCID = ROCID;
            this.info = info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSessionTransactionKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSessionTransactionKeyResponse", Namespace="http://www.chtd.com.tw", Order=0)]
        public ES.Service.GSP1.GetSessionTransactionKeyResponseBody Body;
        
        public GetSessionTransactionKeyResponse() {
        }
        
        public GetSessionTransactionKeyResponse(ES.Service.GSP1.GetSessionTransactionKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.chtd.com.tw")]
    public partial class GetSessionTransactionKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ES.Service.GSP1.SessionKeyResponse GetSessionTransactionKeyResult;
        
        public GetSessionTransactionKeyResponseBody() {
        }
        
        public GetSessionTransactionKeyResponseBody(ES.Service.GSP1.SessionKeyResponse GetSessionTransactionKeyResult) {
            this.GetSessionTransactionKeyResult = GetSessionTransactionKeyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TransactionServiceSoapChannel : ES.Service.GSP1.TransactionServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionServiceSoapClient : System.ServiceModel.ClientBase<ES.Service.GSP1.TransactionServiceSoap>, ES.Service.GSP1.TransactionServiceSoap {
        
        public TransactionServiceSoapClient() {
        }
        
        public TransactionServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ES.Service.GSP1.GetSessionTransactionKeyResponse ES.Service.GSP1.TransactionServiceSoap.GetSessionTransactionKey(ES.Service.GSP1.GetSessionTransactionKeyRequest request) {
            return base.Channel.GetSessionTransactionKey(request);
        }
        
        public ES.Service.GSP1.SessionKeyResponse GetSessionTransactionKey(string ConnectionAccount, string ConnectionPwd, string ClientIP, string ROCID, ES.Service.GSP1.PaymentInfo[] info) {
            ES.Service.GSP1.GetSessionTransactionKeyRequest inValue = new ES.Service.GSP1.GetSessionTransactionKeyRequest();
            inValue.Body = new ES.Service.GSP1.GetSessionTransactionKeyRequestBody();
            inValue.Body.ConnectionAccount = ConnectionAccount;
            inValue.Body.ConnectionPwd = ConnectionPwd;
            inValue.Body.ClientIP = ClientIP;
            inValue.Body.ROCID = ROCID;
            inValue.Body.info = info;
            ES.Service.GSP1.GetSessionTransactionKeyResponse retVal = ((ES.Service.GSP1.TransactionServiceSoap)(this)).GetSessionTransactionKey(inValue);
            return retVal.Body.GetSessionTransactionKeyResult;
        }
    }
}
