-- 更新系統操作服務諮詢電話
UPDATE SETUP 
SET SETUP_VAL = '(02)7730-7378',
    UPD_TIME = GETDATE(),
    UPD_FUN_CD = 'DEPLOY-20251204',
    UPD_ACC = 'SYSTEM'
WHERE SETUP_CD = 'SERVICETEL';

-- 顯示更新後的結果
SELECT SETUP_CD, SETUP_DESC, SETUP_VAL 
FROM SETUP 
WHERE SETUP_CD = 'SERVICETEL';

